adapters:
  openai: OpenAIAdapter
logger_file: ./log/prompt.log
llms:
  SiliconFlow:
    adapter: openai
    url: https://api.siliconflow.cn/v1/
    api_key: ENV["APIKey"]
    default_model: Qwen/Qwen2.5-7B-Instruct
  deepseek:
    adapter: openai
    url: https://api.deepseek.com
    api_key: ENV["DSKEY"]
    default_model: deepseek-chat
  llamacpp:
    adapter: openai
    url: http://localhost:8080/    
default_llm: siliconflow
worker_path: "./agents/workers"
template_path: "./agents/templates"